version: "3.8"

services:
  db:
    image: postgres
    container_name: local_pgdb
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: shegami
      POSTGRES_PASSWORD: 123456789
    volumes:
      - local_pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: shegami24@gmail.com
      PGADMIN_DEFAULT_PASSWORD: 123456789
    volumes:
      - pgadmin-data:/var/lib/pgadmin

  redis:
    image: redis:latest
    container_name: redis_container
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  redisinsight:
    image: redis/redisinsight:latest
    container_name: redisinsight_container
    restart: always
    ports:
      - "5540:5540"
    volumes:
      - redisinsight_data:/db

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq_container
    restart: always
    ports:
      - "5672:5672"   # RabbitMQ broker
      - "15672:15672" # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

volumes:
  local_pgdata:
  pgadmin-data:
  redis_data:
  redisinsight_data:
