version: "3.8"

services:
  db:
    image: postgres:17-alpine
    container_name: local_pgdb
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: shegami
      POSTGRES_PASSWORD: 123456789
    volumes:
      - local_pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: shegami24@gmail.com
      PGADMIN_DEFAULT_PASSWORD: 123456789
    volumes:
      - pgadmin-data:/var/lib/pgadmin

  redis:
    image: redis:latest
    container_name: redis_container
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  redisinsight:
    image: redis/redisinsight:latest
    container_name: redisinsight_container
    restart: always
    ports:
      - "5540:5540"
    volumes:
      - redisinsight_data:/db

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq_container
    restart: always
    ports:
      - "5672:5672"   # RabbitMQ broker
      - "15672:15672" # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  # --- LOCAL S3 (rustfs) ---
  rustfs:
    image: rustfs/rustfs:1.0.0-alpha.89-glibc
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      RUSTFS_ACCESS_KEY: rustfsadmin
      RUSTFS_SECRET_KEY: rustfsadmin
    volumes:
      - rustfs_data:/data
      - rustfs_logs:/logs

  # --- LOCLA MAILING SMTP FOR SENDING AND CATCHING ALL OUTGOING EMAILS
  mailhog:
    image: mailhog/mailhog:latest
    container_name: mailhog_container
    restart: always
    ports:
      - "1025:1025" # SMTP server port
      - "8025:8025" # Web UI port
    logging:
      driver: "json-file"
      options:
        max-size: "10m"

volumes:
  local_pgdata:
  pgadmin-data:
  redis_data:
  redisinsight_data:
  rustfs_data:
  rustfs_logs: