spring.application.name=hr-sass
server.port=8081

spring.profiles.active=local

rsa.public-key=classpath:certs/public.pem
rsa.private-key=classpath:certs/private.pem
# Postgresql Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/hr-saas?createDatabaseIfNotExist=true
spring.datasource.username=shegami
spring.datasource.password=123456789
# Hibernate Configuration
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true


# Redis config
spring.data.redis.host=localhost
spring.data.redis.port=6379

# Rabbitmq config
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
spring.rabbitmq.listener.simple.retry.enabled=true
spring.rabbitmq.listener.simple.retry.initial-interval=1000ms
spring.rabbitmq.listener.simple.retry.max-attempts=3
spring.rabbitmq.listener.simple.retry.max-interval=10000ms
spring.rabbitmq.listener.simple.retry.multiplier=2.0
spring.rabbitmq.listener.simple.acknowledge-mode=auto

# Aws s3 config
aws.s3.endpoint=http://localhost:9000
aws.s3.access-key: shegami
aws.s3.secret-key: 123456789
aws.s3.region: us-east-1
aws.s3.bucket-name: hr-esn-saas

spring:
mail:
host: localhost
port: 1025


# Email Configuration
spring.mail.host=localhost
spring.mail.port=1025
spring.mail.properties.mail.smtp.auth=false
spring.mail.properties.mail.smtp.starttls.enable=false

